@startuml

!include <C4/C4_Component>

title Component diagram for authentication and authorization service

Container_Boundary(auth, "Auth microservice") {
    Component(auth_controller, "Auth Controller")
    Component(auth_service, "Auth Service")
    Component(token_service, "Token Service")
    Rel(auth_controller, auth_service, "")
    Rel_R(auth_service, token_service, "")
}

Container(users, "Users Service", "Java, Spring Boot", "Manage user information")
Container(api_gateway, "API Gateway")

Rel_D(api_gateway, auth_controller, "Authenticate user")
Rel_D(auth_service, users, "Create JWT token")


@enduml
